Multiples of 3 and 5 V_2
SamiraMunoz/Ruby_Exercises pull request #1
Opened 2019-07-18 19:15 UTC by SamiraMunoz

2019-07-19 20:59 UTC, gealgaro commented on Exercise_1.rb
> +class Multiples_3_and_5
No estas usando el naming convention adecuado. Debe ser Camel Case

2019-07-19 20:59 UTC, gealgaro commented on Exercise_1.rb
> +  def sum_multiples()
Los métodos que no reciben parametros no es necesario ponerle los paréntesis

2019-07-19 21:00 UTC, gealgaro commented on Exercise_1.rb
> +      puts "The sum of all multiples of 3 or 5 below 1000 is: #{sum}"
El método debe cumplir una tarea específica. No debería escribirse en pantalla desde dentro del método

2019-07-19 21:01 UTC, gealgaro commented on Exercise_1.rb
> +exercise.sum_multiples()
Al invocar un método que no recibe parámetros, no es necesario poner los paréntesis

2019-07-19 21:02 UTC, gealgaro commented on Exercise_1.rb
> +    sum  = (1...1000).select { |num| (num % 3) == 0 || (num % 5) == 0 }.sum
Sería interesante que agregaras una segunda implementación usando `inject` de ruby

2019-07-23 17:12 UTC, danielosorio83 requested changes

2019-07-23 17:12 UTC, danielosorio83 commented on Exercise_1.rb
> +    sum  = (1...1000).select { |num| (num % 3) == 0 || (num % 5) == 0 }.sum
que pasa si yo no quiero que sea 1000? sino otro numero? los rangos debes tratar de costumizarlos... el inicial por defecto puede ser 1 y el final 10 o 1000 o el que sea, pero que puedan ser parametizables

2019-07-23 22:57 UTC, danielosorio83 requested changes

2019-07-23 22:57 UTC, danielosorio83 commented on Exercise_1_Parametros.rb
> +    sum  = (1...@num).select { |num| (num % 3) == 0 || (num % 5) == 0 }.sum
si corro el codigo me dio este error en esta linea
```
undefined method `sum' for #<Array:0x007fa7b20d4290> (NoMethodError)
```

2019-07-24 17:19 UTC, danielosorio83 requested changes

2019-07-24 17:19 UTC, danielosorio83 commented on Exercise_1.rb
> +    (1...1000).select { |num| (num % 3) == 0 || (num % 5) == 0 }.sum
me sigue saliendo este error cuando corro el codigo:
```
'sum_multiples': undefined method 'sum' for #<Array:0x007f9c668a8b30> (NoMethodError)
```

2019-07-24 19:23 UTC, danielosorio83 approved these changes

2019-07-24 19:23 UTC, merged