10001st Prime test
SamiraMunoz/Ruby_Exercises pull request #13
Opened 2019-07-26 22:18 UTC by SamiraMunoz

2019-07-26 22:23 UTC, danielosorio83 requested changes

2019-07-26 22:23 UTC, danielosorio83 commented on Test/Exercise_5_Samira_test.rb
> +    assert_match 'The argument is not an integer negative', err.message
de hecho es un numero negativo. el mensaje estaria incorrecto para este caso

2019-07-26 22:23 UTC, danielosorio83 commented on Test/Exercise_5_test.rb
> +require '../Exercise_5.rb'
le puedes agregar mes test a ver que te arroja la libreria `Prime` para que compares con el otro archivo

2019-07-29 22:24 UTC, danielosorio83 requested changes

2019-07-29 22:24 UTC, danielosorio83 commented on Exercise_5.rb
> +class PrimeNumber < Validation
lo mismo que te dije en el otro PR

2019-07-29 22:24 UTC, danielosorio83 commented on Exercise_5.rb
> +class PrimeNumber < Validation
y aqui te quedaron las clases de error

2019-07-29 22:47 UTC, danielosorio83 requested changes

2019-07-29 22:47 UTC, danielosorio83 commented on Exercise_5.rb
>  class PrimeNumber < Validation
si lo vas a incluir, no es necesario que la clase herede de Validaton

2019-07-29 22:47 UTC, danielosorio83 commented on Exercise_5.rb
>  class PrimeNumber < Validation
asi como hiciste en el otro archivo

2019-07-29 22:50 UTC, danielosorio83 approved these changes

2019-07-29 22:50 UTC, SamiraMunoz commented on Exercise_5.rb
>  class PrimeNumber < Validation
Ya

2019-07-29 22:50 UTC, danielosorio83 approved these changes

2019-07-29 22:51 UTC, merged