Fibonacci V_2
SamiraMunoz/Ruby_Exercises pull request #2
Opened 2019-07-18 19:16 UTC by SamiraMunoz

2019-07-19 21:03 UTC, gealgaro commented on Exercise_2.rb
> +  def sum_even()
Los parentesis

2019-07-19 21:08 UTC, gealgaro commented on Exercise_2.rb
> +    sum = fibonacci.select { |c| c.even? && c < 4_000_000}.sum
No es necesario iterar dos veces para extraer los pares. Si puedes comparar dentro del `while`

2019-07-19 21:09 UTC, gealgaro commented on Exercise_2.rb
> +    puts "The sum of the even values of the fibonacci series up to 4000000 is: #{sum}"
EL metodo debe retornar un valor, no imprimir el resultado

2019-07-19 21:09 UTC, gealgaro commented on Exercise_2.rb
> +exercise.sum_even()
Los parentesis

2019-07-19 21:10 UTC, gealgaro commented on Exercise_2.rb
> +exercise = Fibonacci.new
"naming conventions"

El nombre de la variable no es diciente con respecto a la clase

2019-07-19 21:10 UTC, gealgaro commented on Exercise_2.rb
> +    while c < 4_000_000
Reto: Usar los metodos de ruby para iterar. Por ejemplo collect o map o select

2019-07-23 17:09 UTC, danielosorio83 requested changes

2019-07-23 17:09 UTC, danielosorio83 commented on Exercise_2.rb
> +      fibonacci << c if c.even?
esta pregunta aqui es anticipada. ya que en la primera iteracion pregunta por el `c = 1` y ya tu sabes... ¿funcionaria igual si la colocas debajo de `c = a + b`?

2019-07-23 17:09 UTC, danielosorio83 commented on Exercise_2.rb
> +      break if c > 4_000_000
si esta linea depende del valor de c... es necesario hacer `a = b; b = c`? donde quedaria mejor esta linea?

2019-07-23 22:56 UTC, danielosorio83 approved these changes

2019-07-23 22:56 UTC, merged