Largest prime factor V_2
SamiraMunoz/Ruby_Exercises pull request #3
Opened 2019-07-18 19:23 UTC by SamiraMunoz

2019-07-19 21:12 UTC, gealgaro commented on Exercise_3.rb
> +class Factors
El nombre de la clase no es intuitivo. Trata de usar un nombre más diciente

2019-07-19 21:13 UTC, gealgaro commented on Exercise_3.rb
> +  def factor(finality)
Que tal `largest_prime_factor` como nombre del método?

2019-07-19 21:13 UTC, gealgaro commented on Exercise_3.rb
> +    puts "The factors of #{finality} are: "
El método debe retornar un valor, no escribir el resultado

2019-07-19 21:14 UTC, gealgaro commented on Exercise_3.rb
> +  def factor(finality)
El nombre del parámetro/argumento no es intuitivo

2019-07-19 21:15 UTC, gealgaro commented on Exercise_3.rb
> +exercise = Factors.new
El nombre de la variable de instancia no concuerda con la clase

2019-07-19 21:15 UTC, gealgaro commented on Exercise_3.rb
> +exercise = Factors.new
Reto o Sugerencia: Que el número sea un atributo de la clase y se pase por parametro en el constructor

2019-07-19 21:18 UTC, gealgaro commented on Exercise_3.rb
> +      finality = finality/num
Stykeguide convention. Las operaciones deben estar separadas con un espacio

2019-07-19 21:19 UTC, gealgaro commented on Exercise_3.rb
> +      puts "#{num} is factor."
Este puts no debe ir en el metodo

2019-07-23 16:34 UTC, danielosorio83 requested changes

2019-07-23 16:34 UTC, danielosorio83 commented on Exercise_3.rb
> +    factors.each { |num| num }
que quieres con esto? esto devuelve un array en el metodo

2019-07-23 16:34 UTC, danielosorio83 commented on Exercise_3.rb
> +    factors.each { |num| num }
si no me equivoco es que aqui se quiere es el ultimo primo

2019-07-23 19:50 UTC, danielosorio83 approved these changes

2019-07-23 19:50 UTC, merged