10001st prime V_2
SamiraMunoz/Ruby_Exercises pull request #5
Opened 2019-07-18 19:24 UTC by SamiraMunoz

2019-07-19 21:28 UTC, gealgaro commented on Exercise_5.rb
> +require 'prime'
+1 por la investigación sobre `prime`

2019-07-19 21:29 UTC, gealgaro commented on Exercise_5.rb
> +class Prime_10001
Naming conventions: Class name

2019-07-19 21:29 UTC, gealgaro commented on Exercise_5.rb
> +  def prime_10001
Ponerle un nombre mas diciente

2019-07-19 21:29 UTC, gealgaro commented on Exercise_5.rb
> +    puts "The 10 001st prime number is: #{prime.max}"
Ojo con el puts

2019-07-19 21:30 UTC, gealgaro commented
Agregar las dos versiones. Usando prime de ruby y manualmente

2019-07-23 16:25 UTC, danielosorio83 requested changes

2019-07-23 16:25 UTC, danielosorio83 commented on Exercise_5_Samira.rb
> +puts "The 10 001st prime number is: #{prime.primes}."
no pude probar eso... el codigo se quedo pegado

2019-07-23 16:26 UTC, danielosorio83 commented
@SamiraMunoz revisa el conflicto

2019-07-24 16:05 UTC, danielosorio83 approved these changes
@SamiraMunoz lo voy a aprobar a pesar que `Exercise_5_Samira.rb` se demora bastante, pero como tienes el otro q si lo hace rapido creo q entendiste el punto.

2019-07-24 16:05 UTC, merged