Palindrome V_2
SamiraMunoz/Ruby_Exercises pull request #6
Opened 2019-07-18 19:24 UTC by SamiraMunoz

2019-07-19 21:30 UTC, gealgaro commented on Exercise_6.rb
> +  	puts word == word.reverse ? "Is palindrome" : "It's not palindrome"
Ojo con el puts

2019-07-19 21:31 UTC, gealgaro commented
Tarea: Implementar el metodo reverse

2019-07-19 21:33 UTC, gealgaro commented
Agregar una version adicional, usando el método reverse hecho por ti @SamiraMunoz

2019-07-23 16:17 UTC, danielosorio83 requested changes

2019-07-23 16:17 UTC, danielosorio83 commented on Exercise_6_Reverse.rb
> +  	@word == @word.reverse ? true : false
`@word == @word.reverse` ya devuelve true/false de por si.. no es necesario hacerle una condicion de una linea para devolver `true` o `false` si la condicion lo hace

2019-07-23 16:17 UTC, danielosorio83 commented on Exercise_6_Reverse.rb
> +  def palindrome_word
los metodos que devuelven un boolean se coloca un `?` al final del nombre del metodo... revisa https://github.com/alemohamad/ruby-style-guide/blob/master/README-esLA.md

2019-07-23 16:17 UTC, danielosorio83 commented on Exercise_6_Reverse.rb
> +  def palindrome_word
otra cosa, la palabra `palindrome` en el nombre del metodo seria redundante ya que la clase lo dice.. que otra manera se te ocurre para renombrar este metodo?

2019-07-23 20:32 UTC, danielosorio83 requested changes

2019-07-23 20:32 UTC, danielosorio83 commented on Exercise_6_Reverse.rb
> +puts is_palindrome.equal_letters? == true ? "Is palindrome" : "It's not palindrome"
la comparacion de en una condicion para objectos booleanos no es necesaria.
`is_palindrome.equal_letters? == true` es igual `is_palindrome.equal_letters?`

2019-07-23 20:55 UTC, danielosorio83 requested changes

2019-07-23 20:55 UTC, danielosorio83 commented on Exercise_6_Reverse.rb
> +  	@word == @word.reverse
que le paso a la tabulacion en esta linea?

2019-07-23 20:55 UTC, danielosorio83 commented on Exercise_6_Samira.rb
> +  def palindrome_word
los metodos que devuelven booleano se les coloca `?` al final del metodo

2019-07-23 20:55 UTC, danielosorio83 commented on Exercise_6_Samira.rb
> +    counter == end_cycle ? true : false
mismo caso de la condicion booleana

2019-07-23 20:55 UTC, danielosorio83 commented on Exercise_6_Samira.rb
> +puts is_palindrome.palindrome_word == true ? "Is palindrome" : "It's not palindrome"
mismo caso que resolviste sobre la condicion que devuelve true o false

2019-07-23 20:55 UTC, danielosorio83 commented on Exercise_6_Samira.rb
> +  def palindrome_word
en el otro archivo tienes el ejemplo

2019-07-24 14:45 UTC, danielosorio83 requested changes

2019-07-24 14:45 UTC, danielosorio83 commented on Exercise_6_Samira.rb
> +puts is_palindrome.palindrome_word ? "Is palindrome" : "It's not palindrome"
recuerda como deben llamarse los metodos que devuelven booleano

2019-07-24 14:45 UTC, danielosorio83 commented on Exercise_6_Samira.rb
>  is_palindrome = Palindrome.new(word)
`is_palindrome` no es un buen nombre para la instancia de un objecto de una clase

2019-07-24 16:14 UTC, danielosorio83 requested changes

2019-07-24 16:14 UTC, danielosorio83 commented on Exercise_6_Samira.rb
> +verification = Palindrome.new(word)
@SamiraMunoz si tuvieras un archivo de mil lineas y te encuentras con una variable que se llame `verification`, te daria idea de que es un objecto `Palindrome`? o tendrias que buscar por todo el archivo donde inicializaste la variable para ver que es?

2019-07-24 17:18 UTC, danielosorio83 approved these changes

2019-07-24 17:18 UTC, merged